CC=gcc
CFLAGS=-O2 -std=c99
CXXFLAGS=-O2

all: BOTNAME

mm-client.o: client.c client.h

BOTNAME.o: BOTNAME.c client.h
BOTNAME: client.o BOTNAME.o
	${CC} ${CFLAGS} -o $@ $^ -lm

clean:
	rm -f *.o

fresh: clean all

